[package]
name = "midi-daw"
version = "0.1.0"
edition = "2024"

[features]
default = ["pyo3"]
pyo3 = ["midi-daw-types/pyo3"]

[dependencies]
actix = "0.13"
actix-broker = "0.4"
actix-web = "4.13"
actix-ws = "0.3"
async-std = { version = "1.13.1", features = [
  "async-attributes",
  "async-process",
  "futures-core",
] }
bincode = "2.0.1"
crossbeam = { version = "0.8", features = ["crossbeam-channel"] }
futures = "0.3"
futures-lite = "2.6"
fx-hash = { version = "0.1", features = ["nightly"] }
http-body-util = "0.1"
hyper = { version = "1.9", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client", "http1", "tokio"] }
hyperlocal = { version = "0.9", features = ["hyper-util"] }
jack = { version = "0.13", features = ["controller"] }
midi-daw-types = { version = "0.1.0", path = "../midi-daw-types", default-features = false }
midi-msg = "0.8"
midir = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.50", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
tracing = { version = "0.1", features = ["async-await"] }
tracing-actix-web = "0.7"
tracing-bunyan-formatter = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing"] }
uuid = { version = "1.23", features = ["v4"] }
xdg = { version = "3.0", features = ["serde"] }
