_:
  @just -l

mb:
  rlwrap -z "$PWD/empty-line.py" http ws://127.0.0.1:8080/message-bus

req:
  http http+unix://%2Ftmp%2Fmidi-daw.sock/midi

test-seq:
  echo '"new-seq"' | http post http://midi-daw.local:8080/sequence/new
  http post http://midi-daw.local:8080/sequence/set-dev < test-json/set-dev.json
  http post http://midi-daw.local:8080/sequence/add-note < test-json/add-note.json
  http post http://midi-daw.local:8080/sequence/play-all

