[package]
name = "midi-daw-types"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "midi_daw_types"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "midi-daw-sync"
path = "./src/midi_daw_sync.rs"

[[bin]]
name = "midi-daw"
path = "./src/midi_daw.rs"

[features]
default = ["pyo3"]
pyo3 = ["dep:pyo3", "dep:pyo3-log", "dep:log"]

[dependencies]
ansi-to-tui = "8.0.1"
bincode = "2.0.1"
bytes = "1.11.1"
clap = { version = "4.6.0", features = ["derive"] }
color-eyre = "0.6.5"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
crossterm = "0.29.0"
enum_dispatch = "0.3"
hound = "3.5"
jack = { version = "0.13.5", features = ["controller"] }
lazy_static = "1.5.0"
log = { version = "0.4", optional = true, features = ["std"] }
midi-msg = "0.8"
midir = { version = "0.10", features = ["jack"] }
musical_scales = "0.2.0"
nix = { version = "0.31.2", features = ["fs"] }
portable-pty = "0.9.0"
pyo3 = { version = "0.28", optional = true }
pyo3-log = { version = "0.13", optional = true }
rack = { git = "https://github.com/calacuda/rack.git", version = "0.4.8", features = ["vst3"] }
ratatui = "0.30.0"
rust-fuzzy-search = "0.1.1"
rustc-hash = "2.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spmc = "0.3.0"
tokio = { version = "1.51.1", default-features = false, features = ["macros", "rt", "rt-multi-thread", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tui-term = "0.3.4"

# cxx-juce = { git = "https://github.com/JamesHallowell/cxx-juce", version = "0.8.0", features = ["juce-8", "juce_audio_processors", "vst3"] }
