[package]
name = "midi-daw-types"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "midi_daw_types"
crate-type = ["cdylib", "rlib"]

[features]
default = ["pyo3"]
pyo3 = ["dep:pyo3", "dep:pyo3-log", "dep:log"]

[dependencies]
bincode = "2.0.1"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
enum_dispatch = "0.3"
hound = "3.5"
jack = { version = "0.13", features = ["controller"] }
log = { version = "0.4", optional = true, features = ["std"] }
midi-msg = "0.8"
midir = { version = "0.10.3" }
pyo3 = { version = "0.28", optional = true }
pyo3-log = { version = "0.13", optional = true }
rust-fuzzy-search = "0.1.1"
rustc-hash = "2.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
