#!/usr/bin/bash

pipe_file="/tmp/midi-daw-$(echo $$).pipe"

mkfifo $pipe_file

echo "layout {
    pane split_direction=\"vertical\" {
        pane command=\"jurigged\" {
            args \"-m\" \"IPython\" \"-i\" \"${@:1}\"
        }
        pane command=\"cat\" {
            args \"$pipe_file\"
        }
    }
}" > /tmp/midi-daw.kdl

env JURIGGGED_CODE_REDIRECT="$pipe_file" zellij --layout /tmp/midi-daw.kdl
rm -f /tmp/midi-daw.kdl $pipe_file
