_: 
  @just -l

build:
  RUSTFLAGS='-C link-arg=-lc++_shared -C link-arg=-landroid' ~/.cargo/bin/dx build --platform android --verbose --trace

serve:
  RUSTFLAGS='-C link-arg=-lc++_shared -C link-arg=-landroid' ~/.cargo/bin/dx serve --platform android

test-web:
  ~/.cargo/bin/dx serve --platform web

check:
  ~/.cargo/bin/dx check --platform web
  ~/.cargo/bin/dx check --platform desktop

test-loc:
  WEBKIT_DISABLE_COMPOSITING_MODE=1 ~/.cargo/bin/dx serve --platform desktop

